name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "4.08"
          - "4.12"
          - "4.14"
          - "5.0"
          - "5.2"
        exclude:
          - os: windows-latest
            ocaml-compiler: "4.08"
          - os: windows-latest
            ocaml-compiler: "4.12"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
      if: ${{ matrix.os != 'windows-latest'}}
